button to put cards down
sopra-fs22-group-29/brandi-client pull request #93
Opened 2022-05-22 16:09 UTC by ElenaGrafUZH

2022-05-22 17:57 UTC, EriCreator requested changes
I'm sorry, but this is not the way to do this.
Fetching a possible move is ingame logic and should be handled by websockets in the first place.

The server should check for a possible move at the start of a players turn and send a (websocket) notification if there is no possible move. And this is when you set `movePossible`, which could also be part of our state (maybe right below `playerIndex`). 

The surrender cards endpoint isn't really necessary, but could be implemented if you really want it. Otherwise it's also possible to just randomly highlight one of the available cards.

2022-05-23 15:50 UTC, ElenaGrafUZH commented
> I'm sorry, but this is not the way to do this. Fetching a possible move is ingame logic and should be handled by websockets in the first place.
> 
> The server should check for a possible move at the start of a players turn and send a (websocket) notification if there is no possible move. And this is when you set `movePossible`, which could also be part of our state (maybe right below `playerIndex`).
> 
> The surrender cards endpoint isn't really necessary, but could be implemented if you really want it. Otherwise it's also possible to just randomly highlight one of the available cards.

You can find the changes on the new commit. I hope it's better this way

2022-05-24 07:32 UTC, EriCreator approved these changes

2022-05-24 07:32 UTC, EriCreator commented on src/components/views/BasicBoard.js
> +    state.movePossible = true;
did you test this? this should not work without calling `setState(state);`

2022-05-24 07:32 UTC, EriCreator commented on src/components/views/BasicBoard.js
> +    state.movePossible = true;
```suggestion
    state.movePossible = true;
    setState({ ...state });
```

2022-05-24 07:32 UTC, merged